const mostPlayed = [
  {
    Name: "Rise",
    Artist: "State of Mine",
    Album: "Devil in Disguise",
    Time: 197,
    Plays: 545,
  },
  {
    Name: "Immortals",
    Artist: "Fall Out Boy",
    Album: "American Beauty/American Psycho",
    Time: 189,
    Plays: 308,
  },
  {
    Name: "My Songs Know What You Did In the Dark (Light Em Up)",
    Artist: "Fall Out Boy",
    Album: "Save Rock and Roll",
    Time: 186,
    Plays: 142,
  },
  {
    Name: "Icarus",
    Artist: "Bastille",
    Album: "All This Bad Blood (Deluxe Edition)",
    Time: 225,
    Plays: 123,
  },
  {
    Name: "My Heart Is Broken",
    Artist: "Evanescence",
    Album: "Evanescence (Deluxe Version)",
    Time: 269,
    Plays: 115,
  },
  {
    Name: "This Ain't A Scene, It's An Arms Race",
    Artist: "Fall Out Boy",
    Album: "Infinity On High",
    Time: 212,
    Plays: 114,
  },
  {
    Name: "In the Dark",
    Artist: "Nine Lashes",
    Album: "From Water to War",
    Time: 212,
    Plays: 106,
  },
  {
    Name: "Friction",
    Artist: "Imagine Dragons",
    Album: "Smoke + Mirrors (Deluxe)",
    Time: 201,
    Plays: 107,
  },
  {
    Name: "Castle",
    Artist: "Halsey",
    Album: "BADLANDS (Deluxe Edition)",
    Time: 277,
    Plays: 96,
  },
  {
    Name: "Anthem Of The Lonely",
    Artist: "Nine Lashes",
    Album: "World We View",
    Time: 241,
    Plays: 103,
  },
  {
    Name: "Gold",
    Artist: "Imagine Dragons",
    Album: "Smoke + Mirrors (Deluxe)",
    Time: 216,
    Plays: 100,
  },
  {
    Name: "And We Run (feat. Xzibit)",
    Artist: "Within Temptation",
    Album: "Hydra (Deluxe Edition)",
    Time: 230,
    Plays: 761,
  },
  {
    Name: "Scars",
    Artist: "I Prevail",
    Album: "Lifelines",
    Time: 229,
    Plays: 732,
  },
  {
    Name: "E Be Tins (feat. Mayorkun)",
    Artist: "Dremo",
    Album: "E Be Tins (feat. Mayorkun) - Single",
    Time: 157,
    Plays: 465,
  },
  {
    Name: "Failure",
    Artist: "Breaking Benjamin",
    Album: "Dark Before Dawn",
    Time: 214,
    Plays: 413,
  },
  {
    Name: "Mona Lisa (feat. Kendrick Lamar)",
    Artist: "Lil Wayne",
    Album: "Tha Carter V",
    Time: 324,
    Plays: 371,
  },
  {
    Name: "Never Again",
    Artist: "Breaking Benjamin",
    Album: "Dark Before Dawn",
    Time: 223,
    Plays: 361,
  },
  {
    Name: "Reggaetón Lento (Remix)",
    Artist: "Little Mix & CNCO",
    Album: "Glory Days: The Platinum Edition",
    Time: 188,
    Plays: 333,
  },
  {
    Name: "Holy Father",
    Artist: "Mayorkun & Victony",
    Album: "Back In Office",
    Time: 184,
    Plays: 330,
  },
  {
    Name: "Illuminati",
    Artist: "Madonna",
    Album: "Rebel Heart (SuperDeluxe Edition)",
    Time: 224,
    Plays: 307,
  },
  {
    Name: "Protectors of the Earth",
    Artist: "Two Steps From Hell",
    Album: "Invincible",
    Time: 169,
    Plays: 295,
  },
  {
    Name: "Stuck in Your Head",
    Artist: "I Prevail",
    Album: "Lifelines",
    Time: 214,
    Plays: 274,
  },
  {
    Name: "Denied",
    Artist: "Sonic Syndicate",
    Album: "Only Inhuman (Tour Edition)",
    Time: 231,
    Plays: 261,
  },
  {
    Name: "Twenty To One",
    Artist: "Dave",
    Album: "We're All Alone In This Together",
    Time: 201,
    Plays: 228,
  },
  {
    Name: "Never Stop",
    Artist: "Future",
    Album: "Future Hndrxx Presents: The WIZRD",
    Time: 291,
    Plays: 226,
  },
  {
    Name: "Less Than",
    Artist: "Nine Inch Nails",
    Album: "Add Violence",
    Time: 210,
    Plays: 225,
  },
  {
    Name: "Nobody",
    Artist: "DJ Neptune, Joeboy & Mr Eazi",
    Album: "Nobody - Single",
    Time: 145,
    Plays: 225,
  },
  {
    Name: "Dressed In Black",
    Artist: "Sia",
    Album: "1000 Forms Of Fear",
    Time: 400,
    Plays: 220,
  },
  {
    Name: "Zombie",
    Artist: "Bad Wolves",
    Album: "Zombie - Single",
    Time: 254,
    Plays: 221,
  },
  {
    Name: "See Me Fight (feat. Linea Adamson)",
    Artist: "Two Steps From Hell",
    Album: "Unleashed",
    Time: 334,
    Plays: 215,
  },
  {
    Name: "Roses Remix (feat. Future)",
    Artist: "SAINt JHN",
    Album: "Roses Remix [feat. Future] - Single",
    Time: 187,
    Plays: 217,
  },
  {
    Name: "Do Better",
    Artist: "Olamide",
    Album: "Carpe Diem",
    Time: 192,
    Plays: 212,
  },
  {
    Name: "Physical",
    Artist: "Dua Lipa",
    Album: "Future Nostalgia",
    Time: 193,
    Plays: 210,
  },
  {
    Name: "The Reckoning (feat. Jacoby Shaddix)",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 251,
    Plays: 209,
  },
  {
    Name: "Funky Friday",
    Artist: "Dave & Fredo",
    Album: "Funky Friday - Single",
    Time: 182,
    Plays: 205,
  },
  {
    Name: "DJ Ease My Mind",
    Artist: "Niki & The Dove",
    Album: "Instinct (Deluxe Version)",
    Time: 243,
    Plays: 202,
  },
  {
    Name: "ətˈæk 0N tάɪtn",
    Artist: "Hiroyuki Sawano",
    Album: 'TV Anime "Attack on Titan" (Original Soundtrack)',
    Time: 256,
    Plays: 200,
  },
  {
    Name: "Flight",
    Artist: "Hans Zimmer",
    Album: "Man of Steel (Original Motion Picture Soundtrack) [Deluxe Edition]",
    Time: 258,
    Plays: 197,
  },
  {
    Name: "Mo40",
    Artist: "Rahman Jago, Bad Boy Timz & Barry Jhay",
    Album: "Mo40 - Single",
    Time: 194,
    Plays: 183,
  },
  {
    Name: "Raise Your Banner (feat. Anders Fridén)",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 334,
    Plays: 184,
  },
  {
    Name: "In Your Pocket",
    Artist: "Maroon 5",
    Album: "V (Deluxe)",
    Time: 219,
    Plays: 176,
  },
  {
    Name: "It's You",
    Artist: "Ali Gatie",
    Album: "YOU",
    Time: 212,
    Plays: 173,
  },
  {
    Name: "Of Lagos",
    Artist: "Mayorkun",
    Album: "Of Lagos - Single",
    Time: 165,
    Plays: 171,
  },
  {
    Name: "Archangel",
    Artist: "Two Steps From Hell",
    Album: "Archangel",
    Time: 154,
    Plays: 172,
  },
  {
    Name: "Together We Rise",
    Artist: "Mitchell Broom",
    Album: "Oblivion",
    Time: 207,
    Plays: 169,
  },
  {
    Name: "Rodeo",
    Artist: "Lil Nas X & Cardi B",
    Album: "7 - EP",
    Time: 158,
    Plays: 168,
  },
  {
    Name: "Low (feat. T-Pain)",
    Artist: "Flo Rida",
    Album: "Low (feat. T-Pain) - Single",
    Time: 231,
    Plays: 166,
  },
  {
    Name: "Ricochet",
    Artist: "STARSET",
    Album: "Vessels",
    Time: 310,
    Plays: 167,
  },
  {
    Name: "Alive",
    Artist: "Echoes",
    Album: "Alive - Single",
    Time: 238,
    Plays: 162,
  },
  {
    Name: "Endless War",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 249,
    Plays: 161,
  },
  {
    Name: "WTH>You (feat Chairman Hahn & Aceyalone)",
    Artist: "LINKIN PARK",
    Album: "Reanimation",
    Time: 252,
    Plays: 160,
  },
  {
    Name: "Osanle (feat. Davido)",
    Artist: "Zlatan",
    Album: "Osanle (feat. Davido) - Single",
    Time: 210,
    Plays: 161,
  },
  {
    Name: "Bae",
    Artist: "O.T. Genasis",
    Album: "Bae - Single",
    Time: 156,
    Plays: 157,
  },
  {
    Name: "Mercy Mirror",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 229,
    Plays: 157,
  },
  {
    Name: "Uncover",
    Artist: "Zara Larsson",
    Album: "Introducing",
    Time: 211,
    Plays: 157,
  },
  {
    Name: "Supernova",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 335,
    Plays: 155,
  },
  {
    Name: "Hear Me Now (feat. DIAMANTE)",
    Artist: "Bad Wolves",
    Album: "Hear Me Now (feat. DIAMANTE) - Single",
    Time: 219,
    Plays: 153,
  },
  {
    Name: "Hey DJ (Remix)",
    Artist: "CNCO, Meghan Trainor & Sean Paul",
    Album: "Hey DJ (Remix) - Single",
    Time: 189,
    Plays: 149,
  },
  {
    Name: "Young and Menace",
    Artist: "Fall Out Boy",
    Album: "M A N I A",
    Time: 223,
    Plays: 151,
  },
  {
    Name: "Bury Me Alive",
    Artist: "Self Deception",
    Album: "Endorse the Art - EP",
    Time: 241,
    Plays: 151,
  },
  {
    Name: "Mad World",
    Artist: "Within Temptation",
    Album: "Resist (Extended Deluxe)",
    Time: 297,
    Plays: 148,
  },
  {
    Name: "Shoot Love",
    Artist: "Maroon 5",
    Album: "V (Deluxe)",
    Time: 190,
    Plays: 148,
  },
  {
    Name: "I Love",
    Artist: "Joyner Lucas",
    Album: "I Love - Single",
    Time: 210,
    Plays: 146,
  },
  {
    Name: "(I Just) Died In Your Arms [Epic Trailer Version] [Epic Trailer Version]",
    Artist: "Hidden Citizens",
    Album: "(I Just) Died In Your Arms (Epic Trailer Version) - Single",
    Time: 235,
    Plays: 144,
  },
  {
    Name: "Afterglow",
    Artist: "Nine Lashes",
    Album: "World We View",
    Time: 266,
    Plays: 143,
  },
  {
    Name: "Faithfully",
    Artist: "Shaboozey",
    Album: "Lady Wrangler",
    Time: 219,
    Plays: 143,
  },
  {
    Name: "Lagos Big Boy",
    Artist: "Ajebutter 22",
    Album: "What Happens in Lagos",
    Time: 221,
    Plays: 144,
  },
  {
    Name: "The Matter",
    Artist: "EESKAY",
    Album: "The Matter - Single",
    Time: 148,
    Plays: 141,
  },
  {
    Name: "Daz How Star Do (feat. Teni, Falz & DJ Neptune)",
    Artist: "Skiibii",
    Album: "Daz How Star Do (feat. DJ Neptune, Falz & Teni) - Single",
    Time: 248,
    Plays: 142,
  },
  {
    Name: "Legends",
    Artist: "Sleeping With Sirens",
    Album: "Gossip",
    Time: 222,
    Plays: 141,
  },
  {
    Name: "Never There",
    Artist: "Sum 41",
    Album: "Order in Decline",
    Time: 260,
    Plays: 143,
  },
  {
    Name: "The Unknown",
    Artist: "10 Years",
    Album: "Violent Allies",
    Time: 180,
    Plays: 139,
  },
  {
    Name: "Wake Up in the Sky",
    Artist: "Gucci Mane, Bruno Mars & Kodak Black",
    Album: "Wake Up in the Sky - Single",
    Time: 204,
    Plays: 135,
  },
  {
    Name: "Rumors",
    Artist: "NEFFEX",
    Album: "Rumors - Single",
    Time: 247,
    Plays: 141,
  },
  {
    Name: "Fortnight",
    Artist: "Polo G",
    Album: "Hall of Fame 2.0",
    Time: 129,
    Plays: 134,
  },
  {
    Name: "Zombie",
    Artist: "The Cranberries",
    Album: "No Need to Argue (The Complete Sessions 1994–1995)",
    Time: 306,
    Plays: 132,
  },
  {
    Name: "No Lie (feat. Drake)",
    Artist: "2 Chainz",
    Album: "Based On a T.R.U. Story (Deluxe Version)",
    Time: 237,
    Plays: 131,
  },
  {
    Name: "Rescue Me",
    Artist: "OneRepublic",
    Album: "Rescue Me - Single",
    Time: 158,
    Plays: 129,
  },
  {
    Name: "No Limit (feat. A$AP Rocky & Cardi B)",
    Artist: "G-Eazy",
    Album: "The Beautiful & Damned",
    Time: 245,
    Plays: 128,
  },
  {
    Name: "He Lives in You",
    Artist: "Lebo M",
    Album: "The Lion King (Original Motion Picture Soundtrack)",
    Time: 305,
    Plays: 127,
  },
  {
    Name: "True (feat. Kizz Daniel)",
    Artist: "Mayorkun",
    Album: "True (feat. Kizz Daniel) - Single",
    Time: 217,
    Plays: 127,
  },
  {
    Name: "心を一つに",
    Artist: "Yuki Hayashi",
    Album:
      "「僕のヒーローアカデミア THE MOVIE ヒーローズ:ライジング」オリジナルサウンドトラック",
    Time: 144,
    Plays: 127,
  },
  {
    Name: "Baajo",
    Artist: "Kwesi Arthur & Joeboy",
    Album: "Baajo - Single",
    Time: 160,
    Plays: 127,
  },
  {
    Name: "Bandit",
    Artist: "Juice WRLD & YoungBoy Never Broke Again",
    Album: "Bandit - Single",
    Time: 189,
    Plays: 124,
  },
  {
    Name: "Despacito",
    Artist: "Luis Fonsi & Daddy Yankee",
    Album: "VIDA",
    Time: 229,
    Plays: 123,
  },
  {
    Name: "Reason with Me",
    Artist: "Rudeboy",
    Album: "Reason with Me - Single",
    Time: 251,
    Plays: 123,
  },
  {
    Name: "I Warned Myself",
    Artist: "Charlie Puth",
    Album: "I Warned Myself - Single",
    Time: 159,
    Plays: 121,
  },
  {
    Name: "Heart",
    Artist: "Cyan Kicks",
    Album: "Heart - Single",
    Time: 174,
    Plays: 122,
  },
  {
    Name: "Here We Stand",
    Artist: "Hidden Citizens & Svrcina",
    Album: "Here We Stand - Single",
    Time: 216,
    Plays: 121,
  },
  {
    Name: "Top Off (feat. JAY-Z, Future & Beyoncé)",
    Artist: "DJ Khaled",
    Album: "Father of Asahd",
    Time: 230,
    Plays: 123,
  },
  {
    Name: "Unstoppable",
    Artist: "Sia",
    Album: "This Is Acting (Deluxe Version)",
    Time: 217,
    Plays: 120,
  },
  {
    Name: "Entertain You",
    Artist: "Within Temptation",
    Album: "Shed My Skin - EP",
    Time: 211,
    Plays: 123,
  },
  {
    Name: "Control",
    Artist: "Halsey",
    Album: "BADLANDS (Deluxe Edition)",
    Time: 214,
    Plays: 117,
  },
  {
    Name: "Satellites (Act III)",
    Artist: "Crown the Empire",
    Album: "The Resistance: Rise of the Runaways",
    Time: 127,
    Plays: 117,
  },
  {
    Name: "Silent Running",
    Artist: "Hidden Citizens",
    Album: "",
    Time: 235,
    Plays: 116,
  },
  {
    Name: "WATER",
    Artist: "Salatiel, Pharrell Williams & Beyoncé",
    Album: "The Lion King: The Gift",
    Time: 152,
    Plays: 116,
  },
  {
    Name: "Champion",
    Artist: "Fall Out Boy",
    Album: "M A N I A",
    Time: 192,
    Plays: 115,
  },
  {
    Name: "Bad Liar – Stripped",
    Artist: "Imagine Dragons",
    Album: "Bad Liar – Stripped - Single",
    Time: 253,
    Plays: 114,
  },
  {
    Name: "Tiff",
    Artist: "Simi",
    Album: "Simisola",
    Time: 212,
    Plays: 114,
  },
  {
    Name: "In My Head",
    Artist: "Larry Gaaga & Patoranking",
    Album: "In My Head - Single",
    Time: 194,
    Plays: 113,
  },
  {
    Name: "Escápate Conmigo (feat. Ozuna)",
    Artist: "Wisin",
    Album: "Victory",
    Time: 232,
    Plays: 113,
  },
  {
    Name: "Faded",
    Artist: "Alan Walker",
    Album: "Faded - EP",
    Time: 212,
    Plays: 110,
  },
  {
    Name: "Sin Pijama",
    Artist: "Becky G. & Natti Natasha",
    Album: "MALA SANTA",
    Time: 190,
    Plays: 110,
  },
  {
    Name: "Ricochet (Acoustic Version)",
    Artist: "STARSET",
    Album: "Ricochet (Deluxe) - Single",
    Time: 291,
    Plays: 110,
  },
  {
    Name: "Si No Vuelves",
    Artist: "Gente de Zona",
    Album: "OTRA COSA",
    Time: 215,
    Plays: 111,
  },
  {
    Name: "Professor X",
    Artist: "Dave",
    Album: "Top Boy (A Selection of Music Inspired by the Series)",
    Time: 217,
    Plays: 110,
  },
  {
    Name: "Oceans (Where Feet May Fail) [Reloaded]",
    Artist: "Hillsong UNITED & TAYA",
    Album: "Zion",
    Time: 418,
    Plays: 107,
  },
  {
    Name: "Paralyzed",
    Artist: "NF",
    Album: "Mansion",
    Time: 270,
    Plays: 108,
  },
  {
    Name: "Praise The Lord (Da Shine) [feat. Skepta]",
    Artist: "A$AP Rocky",
    Album: "TESTING",
    Time: 205,
    Plays: 107,
  },
  {
    Name: "Have Fun",
    Artist: "Bad Boy Timz",
    Album: "Have Fun - Single",
    Time: 136,
    Plays: 105,
  },
  {
    Name: "Playing God",
    Artist: "Bullet For My Valentine",
    Album: "Venom (Deluxe Edition)",
    Time: 232,
    Plays: 105,
  },
  {
    Name: "Reggaetón Lento (Bailemos)",
    Artist: "CNCO",
    Album: "Primera Cita",
    Time: 222,
    Plays: 106,
  },
  {
    Name: "Scorned",
    Artist: "Hypnogaja",
    Album: "Audio from Last Night's Dream",
    Time: 223,
    Plays: 105,
  },
  {
    Name: "Selecta (feat. BOJ, Teezee, Fresh L. & Shank)",
    Artist: "DRB Lasgidi",
    Album: "Drb 10",
    Time: 224,
    Plays: 104,
  },
  {
    Name: 'One Punch Man Theme (Slow Version) [From "One Punch Man"]',
    Artist: "Ralpi Composer",
    Album: "Sweet Harp Sounds, Vol. 2",
    Time: 97,
    Plays: 104,
  },
  {
    Name: "Lovely (feat. Charlotte Buchholz)",
    Artist: "Time, The Valuator",
    Album: "Lovely (feat. Charlotte Buchholz) - Single",
    Time: 238,
    Plays: 107,
  },
  {
    Name: "GATTI",
    Artist: "JACKBOYS, Pop Smoke & Travis Scott",
    Album: "JACKBOYS",
    Time: 181,
    Plays: 105,
  },
  {
    Name: "Your Betrayal",
    Artist: "Bullet For My Valentine",
    Album: "Fever",
    Time: 292,
    Plays: 102,
  },
  {
    Name: "P5hng Me A*wy (feat Stephen Richards & Mike Shinoda)",
    Artist: "LINKIN PARK",
    Album: "Reanimation",
    Time: 277,
    Plays: 101,
  },
  {
    Name: "Dusk Till Dawn (feat. Sia) [Radio Edit]",
    Artist: "ZAYN",
    Album: "Dusk Till Dawn (feat. Sia) [Radio Edit] - Single",
    Time: 239,
    Plays: 102,
  },
  {
    Name: "Star Sky",
    Artist: "Two Steps From Hell",
    Album: "Battlecry",
    Time: 330,
    Plays: 100,
  },
  {
    Name: "Dignity",
    Artist: "Bullet For My Valentine",
    Album: "Fever",
    Time: 267,
    Plays: 99,
  },
  {
    Name: "DEALER",
    Artist: "RMR",
    Album: "DEALER - Single",
    Time: 144,
    Plays: 100,
  },
  {
    Name: "I Will Not Bow",
    Artist: "Breaking Benjamin",
    Album: "Dear Agony",
    Time: 216,
    Plays: 99,
  },
  {
    Name: "Bad Husband (feat. X Ambassadors)",
    Artist: "Eminem",
    Album: "Revival",
    Time: 287,
    Plays: 98,
  },
  {
    Name: "Mo Bamba",
    Artist: "Sheck Wes",
    Album: "MUDBOY",
    Time: 183,
    Plays: 97,
  },
  {
    Name: "Fight Back",
    Artist: "NEFFEX",
    Album: "Fight Back - Single",
    Time: 200,
    Plays: 101,
  },
  {
    Name: "Boy in the Bubble",
    Artist: "Alec Benjamin",
    Album: "Narrated for You",
    Time: 181,
    Plays: 93,
  },
  {
    Name: "Umbrella (feat. Jvzel)",
    Artist: "J2",
    Album: "Umbrella (feat. Jvzel) - Single",
    Time: 235,
    Plays: 93,
  },
  {
    Name: "Motley Crew",
    Artist: "Post Malone",
    Album: "Motley Crew - Single",
    Time: 184,
    Plays: 95,
  },
  {
    Name: "Unwanted",
    Artist: "The Strange Familiar",
    Album: "Chasing Shadows",
    Time: 246,
    Plays: 95,
  },
  {
    Name: "To Glory",
    Artist: "Two Steps From Hell",
    Album: "Invincible",
    Time: 275,
    Plays: 93,
  },
  {
    Name: "9 Lives",
    Artist: "Aṣa",
    Album: "Lucid",
    Time: 179,
    Plays: 96,
  },
  {
    Name: "Hey DJ",
    Artist: "CNCO & Yandel",
    Album: "CNCO",
    Time: 206,
    Plays: 92,
  },
  {
    Name: "Writer In the Dark",
    Artist: "Lorde",
    Album: "Melodrama",
    Time: 216,
    Plays: 91,
  },
  {
    Name: "Despacito (feat. Justin Bieber) [Remix]",
    Artist: "Luis Fonsi & Daddy Yankee",
    Album: "Despacito (Remix) [feat. Justin Bieber] - Single",
    Time: 228,
    Plays: 90,
  },
  {
    Name: "Danza Kuduro (feat. Lucenzo)",
    Artist: "Don Omar & Lucenzo",
    Album: "Meet the Orphans",
    Time: 198,
    Plays: 90,
  },
  {
    Name: "Undone",
    Artist: "FFH",
    Album: "",
    Time: 282,
    Plays: 88,
  },
  {
    Name: "S.E.X.",
    Artist: "Madonna",
    Album: "Rebel Heart (SuperDeluxe Edition)",
    Time: 251,
    Plays: 89,
  },
  {
    Name: "Our Darkest Day",
    Artist: "Nine Lashes",
    Album: "World We View",
    Time: 211,
    Plays: 87,
  },
  {
    Name: "The Greatest (feat. Kendrick Lamar)",
    Artist: "Sia",
    Album: "This Is Acting (Deluxe Version)",
    Time: 210,
    Plays: 87,
  },
  {
    Name: "Start a Riot",
    Artist: "DUCKWRTH & Shaboozey",
    Album:
      "Spider-Man: Into the Spider-Verse (Soundtrack From & Inspired by the Motion Picture)",
    Time: 171,
    Plays: 85,
  },
  {
    Name: "Champion",
    Artist: "Fireboy DML & D Smoke",
    Album: "APOLLO",
    Time: 179,
    Plays: 88,
  },
  {
    Name: "Gmail",
    Artist: "Sheck Wes",
    Album: "MUDBOY",
    Time: 216,
    Plays: 86,
  },
  {
    Name: "Drivers License",
    Artist: "Our Last Night",
    Album: "Drivers License - Single",
    Time: 236,
    Plays: 86,
  },
  {
    Name: "I'm Not Utopia",
    Artist: "Entail of Crow",
    Album: "I'm Not Utopia - Single",
    Time: 253,
    Plays: 84,
  },
  {
    Name: "SICKO (feat. GASHI & FAANGS)",
    Artist: "Felix Jaehn",
    Album: "SICKO (feat. GASHI & FAANGS) - Single",
    Time: 157,
    Plays: 83,
  },
  {
    Name: "Trust Your Gut",
    Artist: "Sink the Ship",
    Album: "Persevere",
    Time: 208,
    Plays: 85,
  },
  {
    Name: "PXTA",
    Artist: "Naira Marley",
    Album: "PXTA - Single",
    Time: 208,
    Plays: 82,
  },
  {
    Name: "There Will Be Blood",
    Artist: "Brighter Than a Thousand Suns",
    Album: "Rebirth - EP",
    Time: 194,
    Plays: 81,
  },
  {
    Name: "Alone",
    Artist: "Bullet For My Valentine",
    Album: "Fever",
    Time: 355,
    Plays: 82,
  },
  {
    Name: "Scatter",
    Artist: "Fireboy DML",
    Album: "Laughter, Tears & Goosebumps",
    Time: 164,
    Plays: 82,
  },
  {
    Name: "High",
    Artist: "Adekunle Gold & Davido",
    Album: "High - Single",
    Time: 193,
    Plays: 83,
  },
  {
    Name: "Insomnia",
    Artist: "Daya",
    Album: "Insomnia - Single",
    Time: 179,
    Plays: 81,
  },
  {
    Name: "Clartin",
    Artist: "J Hus",
    Album: "Common Sense",
    Time: 194,
    Plays: 84,
  },
  {
    Name: "Payphone (feat. Wiz Khalifa)",
    Artist: "Maroon 5",
    Album: "Overexposed (Deluxe Version)",
    Time: 231,
    Plays: 80,
  },
  {
    Name: "Where Did It Go?",
    Artist: "Asking Alexandria",
    Album: "Asking Alexandria",
    Time: 193,
    Plays: 79,
  },
  {
    Name: "You Die Or I Do",
    Artist: "Hans Zimmer",
    Album: "Man of Steel (Original Motion Picture Soundtrack) [Deluxe Edition]",
    Time: 193,
    Plays: 80,
  },
  {
    Name: "Dirty Pretty",
    Artist: "In This Moment",
    Album: "Black Widow",
    Time: 247,
    Plays: 81,
  },
  {
    Name: "Collabo (feat. Don Jazzy)",
    Artist: "P-Square",
    Album: "Double Trouble",
    Time: 223,
    Plays: 80,
  },
  {
    Name: "Have Mercy",
    Artist: "Chlöe",
    Album: "Have Mercy - Single",
    Time: 148,
    Plays: 80,
  },
  {
    Name: "Don't Waste My Time",
    Artist: "Krept & Konan",
    Album: "Don't Waste My Time - Single",
    Time: 207,
    Plays: 79,
  },
  {
    Name: "7 rings",
    Artist: "Ariana Grande",
    Album: "thank u, next",
    Time: 178,
    Plays: 78,
  },
  {
    Name: "Do Not Disturb",
    Artist: "Halestorm",
    Album: "Vicious",
    Time: 203,
    Plays: 77,
  },
  {
    Name: "The Bigger Picture",
    Artist: "Lil Baby",
    Album: "The Bigger Picture - Single",
    Time: 252,
    Plays: 80,
  },
  {
    Name: "Numb",
    Artist: "LINKIN PARK",
    Album: "Meteora",
    Time: 187,
    Plays: 79,
  },
  {
    Name: "Runnin",
    Artist: "Mike WiLL Made-It, A$AP Rocky, A$AP Ferg & Nicki Minaj",
    Album: "Creed II: The Album",
    Time: 131,
    Plays: 82,
  },
  {
    Name: "Everybody Knows",
    Artist: "Sigrid",
    Album: "Justice League (Original Motion Picture Soundtrack)",
    Time: 265,
    Plays: 79,
  },
  {
    Name: "Out for Blood",
    Artist: "Sum 41",
    Album: "Order in Decline",
    Time: 216,
    Plays: 78,
  },
  {
    Name: "Think About Us",
    Artist: "Little Mix",
    Album: "LM5 (Deluxe)",
    Time: 235,
    Plays: 76,
  },
  {
    Name: "Might⁺U",
    Artist: "Makayla Phillips",
    Album:
      "「僕のヒーローアカデミア THE MOVIE ヒーローズ:ライジング」オリジナルサウンドトラック",
    Time: 389,
    Plays: 77,
  },
  {
    Name: "In My Own Skin",
    Artist: "Ryan Caraveo",
    Album: "In My Own Skin - Single",
    Time: 200,
    Plays: 78,
  },
  {
    Name: "New Rules",
    Artist: "Dua Lipa",
    Album: "Dua Lipa (Deluxe)",
    Time: 209,
    Plays: 75,
  },
  {
    Name: 'Trapped (feat. Jussie Smollett & Yazz) [From "Empire"]',
    Artist: "Empire Cast",
    Album: 'Trapped (From "Empire") [feat. Jussie Smollett & Yazz] - Single',
    Time: 132,
    Plays: 75,
  },
  {
    Name: "China Plates",
    Artist: "Massive Wagons",
    Album: "Full Nelson",
    Time: 226,
    Plays: 76,
  },
  {
    Name: "Fast Lane",
    Artist: "Palm Trees, Mdl & Abi F Jones",
    Album: "Fast Lane - Single",
    Time: 149,
    Plays: 76,
  },
  {
    Name: "March Madness",
    Artist: "Future",
    Album: "56 Nights",
    Time: 243,
    Plays: 76,
  },
  {
    Name: "Blindside",
    Artist: "Icon for Hire",
    Album: "Blindside - Single",
    Time: 196,
    Plays: 75,
  },
  {
    Name: "Press Rewind",
    Artist: "Lightscape",
    Album: "Circles - EP",
    Time: 231,
    Plays: 74,
  },
  {
    Name: "Telemo (feat. Capasta)",
    Artist: "Gasmilla",
    Album: "Telemo (feat. Capasta) - Single",
    Time: 254,
    Plays: 77,
  },
  {
    Name: "Surviving The Game",
    Artist: "Skillet",
    Album: "Dominion",
    Time: 238,
    Plays: 74,
  },
  {
    Name: "Yoruba Demon",
    Artist: "Slim T & Delali",
    Album: "Yoruba Demon - Single",
    Time: 192,
    Plays: 75,
  },
  {
    Name: "Naira Marley",
    Artist: "Zinoleesky",
    Album: "Naira Marley - Single",
    Time: 133,
    Plays: 74,
  },
  {
    Name: "Show Me a Leader",
    Artist: "Alter Bridge",
    Album: "The Last Hero",
    Time: 305,
    Plays: 72,
  },
  {
    Name: "This Cancer",
    Artist: "A Broken Silence",
    Album: "All the Way Down",
    Time: 192,
    Plays: 72,
  },
  {
    Name: "Iconic (feat. Chance the Rapper & Mike Tyson)",
    Artist: "Madonna",
    Album: "Rebel Heart (SuperDeluxe Edition)",
    Time: 273,
    Plays: 72,
  },
  {
    Name: "Human",
    Artist: "Rag'n'Bone Man",
    Album: "Human (Deluxe)",
    Time: 200,
    Plays: 73,
  },
  {
    Name: "Awake and Alive",
    Artist: "Skillet",
    Album: "Awake (Deluxe Version)",
    Time: 209,
    Plays: 74,
  },
  {
    Name: "Broke In A Minute",
    Artist: "Tory Lanez",
    Album: "The New Toronto 3",
    Time: 132,
    Plays: 75,
  },
  {
    Name: "Ransom",
    Artist: "Lil Tecca",
    Album: "Ransom - Single",
    Time: 131,
    Plays: 72,
  },
  {
    Name: "Free the Animal",
    Artist: "Sia",
    Album: "1000 Forms Of Fear",
    Time: 265,
    Plays: 71,
  },
  {
    Name: "Impossible (feat. Merethe Soltvedt)",
    Artist: "Two Steps From Hell",
    Album: "Unleashed",
    Time: 534,
    Plays: 72,
  },
  {
    Name: "Rise",
    Artist: "Katy Perry",
    Album: "Rise - Single",
    Time: 203,
    Plays: 71,
  },
  {
    Name: "Marlboro (feat. Foreign Heat)",
    Artist: "Prince of Falls",
    Album: "Till We Feel Something",
    Time: 220,
    Plays: 73,
  },
  {
    Name: "There's a Storm Coming",
    Artist: "Dance With the Dead",
    Album: "The Shape",
    Time: 134,
    Plays: 100,
  },
  {
    Name: "Dancer in the Dark",
    Artist: "Marc Philippe",
    Album: "Top Deep Disco Tunes",
    Time: 248,
    Plays: 76,
  },
  {
    Name: "Arcade",
    Artist: "Duncan Laurence",
    Album: "Arcade - Single",
    Time: 183,
    Plays: 71,
  },
  {
    Name: "Certified Loner (No Competition)",
    Artist: "Mayorkun",
    Album: "Certified Loner (No Competition) - Single",
    Time: 165,
    Plays: 149,
  },
  {
    Name: "君の力",
    Artist: "林ゆうき",
    Album:
      "TVアニメ「僕のヒーローアカデミア」 2nd オリジナル・サウンドトラック",
    Time: 173,
    Plays: 72,
  },
  {
    Name: "Believe",
    Artist: "Eminem",
    Album: "Revival",
    Time: 315,
    Plays: 70,
  },
];

export default mostPlayed;
